# Generated by Django 2.2 on 2021-07-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
